### PR TITLE
Adding a host to allow stories to use hooks

### PR DESCRIPTION
**Pull request by czearing**
#### Description of changes
Added a host component to render stories so that hooks within story examples can run in the context of.

This should resolve issue #11 and #2 but there might be a better way to resolve these issues.

### CODE REVIEW

**Comment by alexreardon** [comment]
Awesome! I'll see if i can get this in

**Comment by dzearing** [comment]
We definitely have a few partners who will hit this, as more and more stories/code examples leverage hooks. The workaround is to wrap the story in a component, which will work.

**Comment by alexreardon** [comment]
You can use hooks, it is just using hooks in the function that is provided to storybook that isn't working. I will dive into the types today and figure out the correct path

**Comment by alexreardon** [comment]
I am brushing up against a typing question: what is the expected type of a provided story?

For now we have been using `() => React.Node`. Which is true if you do this:

```js
export app = () => <App />
```

But not true if you do this:

```js
export app = App
```

The docs only list the first pattern, but it looks like the second works too

**Comment by alexreardon** [comment]
According to their internal types, the `storyFn` is `() => ReactNode`

**Comment by alexreardon** [comment]
Okay, this does pass a typecheck:

```ts
const Hook = () => {
  const [count] = useState(1);

  return <div>Using a state hook {count}</div>;
};

const foo: () => React.ReactNode = Hook;
```

**Comment by alexreardon** [comment]
so `() => React.ReactNode` can include hooks

**Comment by alexreardon** [comment]
I'll merge this in and add some tests. I have a locally working fix too

**Pull request merged**
